/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        meta: "#0081FB",
        messenger: "#0084ff",
        twitter: "#55acee",
        linkedin: "#0077b5",
        skype: "#00aff0",
        dropbox: "#007ee5",
        wordpress: "#21759b",
        vimeo: "#1ab7ea",
        slideshare: "#0077b5",
        vk: "#4c75a3",
        tumblr: "#34465d",
        yahoo: "#410093",
        "google-plus": "#dd4b39",
        pinterest: "#bd081c",
        youtube: "#cd201f",
        stumbleupon: "#eb4924",
        reddit: "#ff5700",
        quora: "#b92b27",
        yelp: "#af0606",
        weibo: "#df2029",
        producthunt: "#da552f",
        hackernews: "#ff6600",
        soundcloud: "#ff3300",
        blogger: "#f57d00",
        whatsapp: "#25d366",
        wechat: "#09b83e",
        line: "#00c300",
        medium: "#02b875",
        vine: "#00b489",
        slack: "#3aaf85",
        instagram: "#e4405f",
        dribbble: "#ea4c89",
        flickr: "#ff0084",
        foursquare: "#f94877",
        behance: "#131418",
        snapchat: "#fffc00",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
